- CommonLibSF/include/RE/T/TESForm.h
And some more vfunc definitions/corrections
> feat: added `TESForm` getters

- README.md
A short explanation of the main requirement of the license, with an additional recommendation to read the FSF FAQ.
> docs: Update README.md with explanation of the main license requirement

- CommonLibSF/include/REL/Relocation.h
- CommonLibSF/include/SFSE/Impl/DInputAPI.h
- CommonLibSF/include/SFSE/Impl/PCH.h
- CommonLibSF/include/SFSE/Impl/WinAPI.h
- CommonLibSF/include/SFSE/Trampoline.h
- CommonLibSF/src/REL/Relocation.cpp
- CommonLibSF/src/SFSE/IAT.cpp
- CommonLibSF/src/SFSE/Impl/WinAPI.cpp
- CommonLibSF/src/SFSE/InputMap.cpp
- CommonLibSF/src/SFSE/Logger.cpp
- CommonLibSF/src/SFSE/Trampoline.cpp
This is essentially a port of the work I did for the WinAPI helper in CommonLibF4-NG, with a few minor tweaks. This also involves removing all other windows includes and using WinAPI directly.
I'm not sure why but several files had their formatting busted from an older commit, resulting in gigantic one liners.
> feat: improve WinAPI and its usage

- CommonLibSF/include/RE/F/FormTypes.h
- CommonLibSF/include/SFSE/Impl/PCH.h
- CommonLibSF/include/SFSE/Logger.h
- CommonLibSF/vcpkg.json
- CommonLibSF/xmake.lua
- xmake.lua
ongoing work to remove fmt usage in the project
needs to be tested in cmake and vcpkg
> chore: remove fmt usage

- CommonLibSF/include/RE/B/BSFixedString.h
- CommonLibSF/include/RE/B/BSStringPool.h
- CommonLibSF/include/RE/I/IFunction.h
- CommonLibSF/include/RE/M/MenuOpenCloseEvent.h
- CommonLibSF/include/RE/T/TESFullName.h
- `BSFixedStringW` has not been tested, but they appear to use the same flags in both `GetEntry` functions.
> feat: `BSFixedString` support

- CommonLibSF/include/RE/B/BSStringPool.h
> docs: update `BSStringPool::Entry::_length`

- CommonLibSF/include/REL/ID.h
- CommonLibSF/include/REL/Module.h
- CommonLibSF/include/REL/Relocation.h
- CommonLibSF/include/REL/Version.h
- CommonLibSF/include/SFSE/Interfaces.h
- CommonLibSF/src/REL/ID.cpp
- CommonLibSF/src/REL/Module.cpp
- CommonLibSF/src/REL/Version.cpp
+ Per [meh321's work](https://www.nexusmods.com/starfield/mods/3256), address library integration is added back.
+ Fixed the wrong versionIndependence flags.
> feat: address library integration

- CommonLibSF/include/REL/ID.h
- CommonLibSF/src/REL/ID.cpp
> fix: define `Offset2ID` template constructor in header

- CommonLibSF/include/REL/Relocation.h
- add assignment operator to `REL::Relocation` for `uintptr_t`
> fix: relocation assignment

- CommonLibSF/include/RE/T/TESObjectREFR.h
- CommonLibSF/src/RE/T/TESObjectREFR.cpp
Well there's no naval term for GetSpaceshipParentDock(I've checked) so untill someone has a better idea we'll have to go with that name.
> feat: Add GetSpaceshipParentDock and GetLinkedRef

- CommonLibSF/include/RE/T/TESObjectREFR.h
- CommonLibSF/include/RE/T/TESWorldSpace.h
- CommonLibSF/src/RE/T/TESObjectREFR.cpp
> feat: Add IsSpaceshipDocked and fix excessive namespace for TESWorldspace

- CommonLibSF/include/SFSE/Version.h
> Bump Game Version and SFSE Version for 1.7.33

- .github/workflows/update_pdb.yml
- Runs after `maintenance.yml`
- Builds the library with the `debug-msvc-ninja` preset
- Uploads pdb as an artifact
> feat: add Update PDB action

- CommonLibSF/include/RE/T/TESForm.h
> feat: Add virtual function GetDisplayFullBaseName to TESForm

- CommonLibSF/include/SFSE/API.h
- CommonLibSF/src/SFSE/API.cpp
- CommonLibSF/src/SFSE/Interfaces.cpp
- remove unused `releaseIndex` (`SFSE` doesn't have this)
- formatting
> fix: expose menu api

- CommonLibSF/include/REL/Pattern.h
Couldn't find this in the lib anywhere, so I'm guessing it got lost somehow in the Starfield transition. This is the same as Ryan's code, but I moved it out to a separate file for organization purposes. I also edited the error message to reflect the possibility that two installed mods may be incompatible with each other.
> feat: Pattern matching functionality

- CommonLibSF/include/RE/U/UI.h
- CommonLibSF/include/SFSE/Impl/WinAPI.h
- CommonLibSF/src/SFSE/Impl/WinAPI.cpp
- add `CreateThread` and `Sleep` winapi functions
- add missing `#pragma once`
> feat: winapi

- CommonLibSF/src/RE/A/AIProcess.cpp
- CommonLibSF/src/RE/A/ActorPackage.cpp
> chore: remove empty compilation units

- CommonLibSF/include/RE/A/Actor.h
- CommonLibSF/include/RE/A/ActorState.h
- CommonLibSF/include/RE/I/IMovementPlayerControlsFilter.h
- CommonLibSF/include/RE/I/IMovementState.h
- CommonLibSF/include/RE/I/IMovementStateStore.h
- CommonLibSF/include/RE/I/IStoreAnimationActions.h
- CommonLibSF/include/RE/M/MagicTarget.h
- CommonLibSF/include/RE/P/PlayerCharacter.h
- CommonLibSF/include/RE/T/TESObjectREFR.h
- `Actor::PlayerCharacter()` to `PlayerCharacter::GetSingleton()`
- `Actor::IsPlayerCharacterInChargen()` to `PlayerCharacter::IsInChargen()`
- `BOOL_BITS` and `BOOL_FLAGS` is copied from F4/SSE verbatim and so isn't guaranteed to be 100% accurate. Most flags do match from what I can see.
> feat!: `TESObjectREFR`, `Actor`, `PlayerCharacter` RE

- CommonLibSF/include/REL/ID.h
- CommonLibSF/include/REL/Module.h
- CommonLibSF/include/REL/Relocation.h
- CommonLibSF/include/REL/Version.h
- CommonLibSF/include/SFSE/IAT.h
- CommonLibSF/include/SFSE/InputMap.h
- CommonLibSF/include/SFSE/Trampoline.h
- CommonLibSF/src/REL/ID.cpp
- CommonLibSF/src/REL/Module.cpp
- CommonLibSF/src/SFSE/API.cpp
- CommonLibSF/src/SFSE/IAT.cpp
- CommonLibSF/src/SFSE/InputMap.cpp
- CommonLibSF/src/SFSE/Trampoline.cpp
also change 2nd parameter of `IDDatabase::unpack_file` to const reference
> chore: make stuff constexpr

- CommonLibSF/include/RE/A/Actor.h
- CommonLibSF/include/RE/A/ActorValueStorage.h
- CommonLibSF/include/RE/B/BGSInventoryList.h
- CommonLibSF/include/RE/P/PlayerCharacter.h
- CommonLibSF/include/RE/T/TESObjectREFR.h
- CommonLibSF/src/RE/A/Actor.cpp
- CommonLibSF/src/RE/P/PlayerCharacter.cpp
- Also moved `Actor` and `PlayerCharacter` declarations to source files
> feat: `TESObjectREFR`, `Actor` RE

- CommonLibSF/include/RE/B/BSTArray.h
- CLIB-F4/SFSE implementation.
- Skipped some constructors/assignment operators that required Boost `stl_interfaces::assign`
- Tested out insert/erase in-game and it seems to work as expected
> feat: `BSTArray` container interface

- include/RE/E/Events.h
- include/RE/G/GameMenuBase.h
- fleshed out several events with members and added more in general
> feat: misc events2

- include/REX/REX/Setting.h
> feat: implicit conversion for `REX::TSetting`
