COPYING
EXCEPTIONS
README.md

This adds a GPL3 or later License with exceptions that are conducive to game modding. Specifically, the exceptions:
1. Allow the linking with Starfield and SFSE without requiring the distribution of their source code or that they be treated as GPL too. Starfield is proprietary and SFSE is still considering license choices.
2. Allow the linking of other libraries without requiring that those libraries be distributed as GPL, but the library's source code must be provided. Please note, those libraries may be non-free but free alternatives may be possible given the access to the source code.
Otherwise, the terms of GPL-3-or-later apply. See the FSF FAQ at: https://www.gnu.org/licenses/gpl-faq.en.html

chore: add GPL3 License with EXCEPTIONS

---

.github/workflows/lint_pr_title.yaml

Uses https://github.com/amannn/action-semantic-pull-request.
We will also need to change the default settings to encourage squashes. See
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/ https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests
I typically keep merge commits when the associated commits follow conventional commits. We could prefix with `chore:`
closes #5

ci: enforce conventional commits in PR titles

---

README.md

This explains that the MIT is for historical purposes and gives credit to Ryan for his foundational work.

docs: add credits to commonlibsse and MIT

---

CommonLibSF/include/SFSE/Interfaces.h
CommonLibSF/src/SFSE/API.cpp

Removed unavailable interfaces from SFSE yet.

fix: remove leftover interfaces

---

CommonLibSF/CMakeLists.txt
CommonLibSF/CMakePresets.json
CommonLibSF/vcpkg.json
README.md
build-clang-cl.bat
build-msvc.bat
make-sln-clang-cl.bat
make-sln-msvc.bat

1. Removed `/FI` force include directive flag to accommodate recent [vcpkg port update](https://github.com/Starfield-Reverse-Engineering/Starfield-RE-vcpkg/). This addresses the redefinition error when compiling project with a clean commonblisf vcpkg package.
2. Reverted some notable changes in #19 , see below.
---
Changes reverted:
In [CommonLibSF/CMakePresets.json](https://github.com/Starfield-Reverse-Engineering/CommonLibSF/compare/main...gottyduke:CommonLibSF:main?expand=1#diff-6d621fcc34a299795af75ba4026fa929d2b8b506efda705e332cf7dd06e6904f):
```json
{
"name": "buildtype-debug-msvc",
"hidden": true,
"cacheVariables": {
"CMAKE_BUILD_TYPE": "Debug",
"CMAKE_CXX_FLAGS_DEBUG": "/Od /MDd",
"CMAKE_SHARED_LINKER_FLAGS_DEBUG": "/DEBUG:FULL /LTCG:INCREMENTAL /DEBUGTYPE:FIXUP"
}
}
``` …

fix!: remove `/FI` (#22) and revert some changes in #19

---

.github/update-registry.ps1
.github/workflows/maintenance.yml
CommonLibSF/vcpkg.json
README.md

- Fix some actions warning
- Use new syntax for $GITHUB_OUTPUT
- Pass sha & version to Starfield-RE-vcpkg repo
- I know the Starfield-RE-vcpkg repo only use sha for now, but with this that version can instead be passed from here to keep them synced
- Fix ps version requirement (`Get-Date -AsUTC` was added in 7.1)
- Add proper co-author with bot
I know that @gottyduke had some local stuff for this, please discard this PR if I did anything wrong. Wasn't 100% if we're supposed to use the incremental date-version on this PR as well.
fixes https://github.com/Starfield-Reverse-Engineering/Starfield-RE-vcpkg/issues/6

ci: update to incremental version-date when needed

---

CommonLibSF/.clang-format

Removed deprecated settings and replaced with equivalents: 
```yaml
LineEnding: CRLF
PackConstructorInitializers: BinPack
```

chore: modernize .clang-format

---

CommonLibSF/include/RE/A/ActorValueOwner.h
CommonLibSF/include/RE/B/BSTEvent.h
CommonLibSF/include/RE/I/IAnimationGraphManagerHolder.h
CommonLibSF/include/RE/I/IMovementInterface.h
CommonLibSF/include/RE/I/IPostAnimationChannelUpdateFunctor.h
CommonLibSF/include/RE/N/NiPoint3.h
CommonLibSF/include/RE/T/TESHandleForm.h
CommonLibSF/include/RE/T/TESObjectREFR.h
CommonLibSF/src/RE/I/IAnimationGraphManagerHolder.cpp
CommonLibSF/src/RE/I/IMovementInterface.cpp
CommonLibSF/src/RE/I/IPostAnimationChannelUpdateFunctor.cpp
CommonLibSF/src/RE/T/TESHandleForm.cpp
CommonLibSF/src/RE/T/TESObjectREFR.cpp

- Switched to using `BSTEvent` class definitions from CommonLib, this gets rid of the unreferenced parameter error
- Added some getters and couple of functions
- `IsInSpaceship` was incorrectly defined, it is now `GetAttachedSpaceship` (note the return parameter should be a `NiSmartPointer` which isn't included as of yet)

feat: complete 'TESObjectREFR` inheritance and related classes

---

.gitignore
CommonLibSF/xmake.lua
xmake.lua

Builds with `msvc-cl`, [`xmake`](https://github.com/xmake-io/xmake) does not currently support toolchain switching for packages on windows, so `clang-cl` is off the table for now.
How to build using [`xmake`](https://github.com/xmake-io/xmake):
```cmd
xmake build
```
This will fetch the project's package dependencies if they aren't already installed, and build all default targets. Packages aren't version pinned at the moment, this can be changed later if necessary.
As for options, there is one at the moment, `sfse_xbyak` which you can enable using:
```cmd
xmake config --sfse_xbyak=true
```
If a VS project is desired, one can be generated for you:
```cmd
xmake project -k vsxmake
```
The project kind `vsxmake` still uses `xmake` as the backend for building and such while allowing you to use …

chore: add xmake build support

---

README.md

+ Added various template links for people to choose from(vcpkg port, git submodule and xmake templates).
+ Added xmake package consume instruction.
This complements #35 .

docs: update template links and xmake instruction

---

CommonLibSF/CMakeLists.txt

This option was removed for always enabling xbyak, but not a wise decision, this PR reverts it and defaulted it off.

fix: re-add `SFSE_SUPPORT_XBYAK`

---

CommonLibSF/include/SFSE/API.h
CommonLibSF/include/SFSE/Interfaces.h
CommonLibSF/include/SFSE/Logger.h
CommonLibSF/src/SFSE/API.cpp
CommonLibSF/src/SFSE/Interfaces.cpp
CommonLibSF/src/SFSE/Logger.cpp

When `SFSE::Init` is used, it will now initialize a default spdlog logger.
```cpp
SFSE::Init(a_sfse); // default log file will be automatically created
```
This behavior can be turned off by passing false as the optional second argument:
```cpp
SFSE::Init(a_sfse, false); // default log file is disabled
```
...if you have no need for a log file at all. Keep in mind that this sets the default logger for the module (plugin), you can still modify it's behavior through the spdlog api, such as setting the level, or the pattern.
Some keen eyed may notice that I am also registering an msvc sink, this will not impact performance as spdlog as of a somewhat recent version now checks if a debugger is attached, and if not, the sink is essentially a no-op, with no real cost to performance.
You can test …

feat: add default logger

---

.github/workflows/main_ci.yml

The previous config seemed to use an older version of both MSVC and clang-cl which caused failures on including new headers like `<stdfloat>`--this avoids the errors as it uses newer versions of the toolsets. Also bumped versions for actions. Tested for release builds with MSVC/Ninja and clang-cl/Ninja

refactor: main CI workflow

---

.gitignore
CommonLibSF/cmake/CommonLibSF.cmake
CommonLibSF/cmake/config.cmake.in

`add_commonlibsf_plugin` creates a `Plugin.h` in `${CMAKE_CURRENT_BINARY_DIR}` which contains a plugin declaration as well as the exported `SFSEPluginVersion` function with all the appropriate fields filled in. `Plugin.h` can be included anywhere in a project for easy access to plugin metadata. The new command also takes care of some housekeeping tasks like linking CommonLibSF to the project. Lifted mostly verbatim from CLibNG, tested it and it seems to work fine for me. Example call:
```cmake
add_commonlibsf_plugin(${PROJECT_NAME} AUTHOR ThirdEyeSqueegee SOURCES ${headers} ${sources})
```
See `CommonLibSF.cmake` for other arguments the command can accept 
Closes #8

feat: add add_commonlibsf_plugin CMake command

---

CommonLibSF/CMakeLists.txt
CommonLibSF/include/SFSE/Impl/WinAPI.h

Should fix the unresolved external symbol error for the `UnDecorateSymbolName` family of functions

fix: add dbghelp.lib to cmake + typo

---

CommonLibSF/src/SFSE/Trampoline.cpp

Rather annoyingly xbyak brings in <Windows.h>. The impact is small as xbyak is only included in `Trampoline.cpp`. Consumers (plugins) should be fine as long as they include xbyak after CommonLibSF.

fix: xbyak brings in <Windows.h>

---

CommonLibSF/include/SFSE/Impl/PCH.h
CommonLibSF/include/SFSE/Logger.h

`spdlog`'s vcpkg port doesn't build in c++20 or higher, so features like `std::format_string` aren't available. For now use `spdlog::format_string_t` to automatically pick an available format string.

fix: use available format_string for now

---

CommonLibSF/include/RE/B/BGSEditorID.h
CommonLibSF/include/RE/B/BGSLocalizedString.h

The official name for `BGSEditorID` isn't referenced anywhere but this class is exclusively used for form editorIDs (which are accessed via the `TESForm::Get/SetFormEditorID` functions)

feat: `BGSLocalizedString`, `BGSEditorID`

---

.github/workflows/maintenance.yml

This should ensure that there's no overlap between CI runs in case multiple pull requests are merged consecutively within a short period. I noticed the vcpkg repo update tends to fail if the repository dispatch event is sent by 2 or more overlapping workflows

feat: add concurrency key to maintenance.yml

---

CommonLibSF/include/SFSE/Interfaces.h

Also add an overload for `PluginVersion` which accepts a `REL::Version`
Related: #65

feat: add `SFSEPluginPreload` and `SFSEPluginVersion` macros

---

CommonLibSF/include/REL/ID.h
CommonLibSF/include/REL/Module.h
CommonLibSF/include/REL/Offset.h
CommonLibSF/include/REL/Relocation.h
CommonLibSF/include/REL/Version.h

- moved `Offset` to it's own header
- some formatting changes

feat: mark Relocation constructors as explicit

---

CommonLibSF/include/RE/Starfield.h
CommonLibSF/include/RE/T/TESObjectCELL.h
CommonLibSF/include/RE/T/TESObjectREFR.h
CommonLibSF/include/RE/T/TESWorldSpace.h
CommonLibSF/src/RE/T/TESObjectREFR.cpp

I realised that I placed TESWorldspace.h to \W\ subfolder on the previous pull request.
This pull request should account for all previously requested changes.

feat: Add TESWorldspace.h, decoding of TESObjectCell, GetParentWorldSpace for TESObjectRef* 

---

CommonLibSF/include/RE/C/ConsoleLog.h

`ConsoleLog::Print` accepts a variadic *object* and should be called `VPrint`, while `Print` accepts variadic *arguments*.
This might cause Squeegee to have an aneurism, but I don't think very many people were paying attention when things were added a while ago. I do agree that pr's should stay in the oven a while longer to catch things like this.
PS: Still not entirely used to conventional commits.
PPS: All hail the march of progress!

fix!: consolelog print/vprint

---

CommonLibSF/include/RE/B/BGSLocation.h
CommonLibSF/include/RE/T/TESObjectREFR.h
CommonLibSF/src/RE/T/TESObjectREFR.cpp

They seem like native functions to me ¯\_(ツ)_/¯.
TESFullName in BGSLocation is confirmed by testing.

feat: Add GetCurrentLocation() and GetSpaceshipPilot() for TESObjectREFR*, add TESFullName to  BGSLocation

---

CommonLibSF/include/RE/T/TESObjectREFR.h
CommonLibSF/src/RE/T/TESObjectREFR.cpp

- The argument is still unknown but it seems to be checking interior cell type (or state). 
- Also renamed `TESObjectREFR::GetAttachedSpaceship` to `TESObjectREFR::GetSpaceship` to match the recently added functions.

fix!: add missing bool argument to `TESObjectREFR::IsInSpace`, `TESObjectREFR::GetAttachedSpaceship`

---

CommonLibSF/include/SFSE/Interfaces.h

These should be bitfields, like `TESForm::formFlags` for example.

fix: SFSE plugin version data address/structure independence bits

---

CommonLibSF/include/SFSE/Impl/Stubs.h
CommonLibSF/include/SFSE/Interfaces.h
CommonLibSF/src/SFSE/API.cpp
CommonLibSF/src/SFSE/Interfaces.cpp

There are no `IMenu` classes yet so this is just the `SFSE` machinery.
The version number for `MessagingInterface` was incorrectly set to 2, it should be 1 as currently set in `SFSE`. This was likely a result of copy & paste from CLibSSE.
PS: I also named the enums for type discovery. I didn't make them `enum class` as that would be a breaking change and overkill.

feat: add MenuInterface + enum names

---

CommonLibSF/cmake/CommonLibSF.cmake

Tested by created a plugin using `add_commonlibsf_plugin`
Still producing this in Plugin.h
```cpp
data.UsesAddressLibrary(true);
data.IsLayoutDependent(true);
```

fix: commonlibsf cmake variable naming

---

CommonLibSF/include/RE/S/Script.h
CommonLibSF/include/RE/U/UI.h

- add `Script::GetConsoleCommands` and `Script::GetScriptCommands`, these return a span allowing you to iterate over all of the commands.
- change the `GetFirst` functions to return a pointer to the command rather than a copy
With the new functions one could achieve pretty much the same result as the `GetFirst` functions by calling `front()` on the span, which begs the question: do we keep the old ones?

feat!: script commands

---

CommonLibSF/include/REL/Pattern.h
CommonLibSF/include/REL/REL.h
CommonLibSF/include/SFSE/Impl/PCH.h

modifies #109 by Exit-9B
- also introduces a new `REL/REL.h` header to take the place of the old all-in-one-header `REL/Relocation.h` used to be, this matches `SFSE/SFSE.h`

feat: pattern matching functionality - continued

---

CommonLibSF/include/RE/B/BSTEvent.h

Unlike F4 it passes in a more complex struct (event + local function lambda)

fix: undefine `BSTEventSource::Notify` argument

---

CommonLibSF/include/RE/C/ConsoleLog.h

- this log function makes use of `std::format` and the benefits that comes with (compile time checking, type representation, numbered fields, etc.) compared to the printf style function.
```cpp
auto log = RE::ConsoleLog::GetSingleton();
log->Log("Value: {}", true);
```
```
Value: true
```

feat: add safer/convenient console log function

---

CommonLibSF/include/RE/N/NiSmartPointer.h
CommonLibSF/include/RE/T/TESForm.h
CommonLibSF/include/RE/T/TESFormRefCount.h
CommonLibSF/src/RE/T/TESFormRefCount.cpp

- the function `DecRefCount` has been moved to `TESForm` because it calls `TESForm` specific vfuncs (0xB, 0xD, 0xE)

feat: add `NiSmartPointer`, support `TESForm` smart pointers

---

CommonLibSF/.clang-format
CommonLibSF/include/SFSE/Impl/PCH.h

- Add requires clause rules to .clang-format to reflect current style, remove some `//` in PCH.h as they're no longer needed with the new rules
- Set FixNamespaceComments to true for consistency, most namespaces already include trailing comments 
- Add the full standard library to PCH.h, it was missing a couple headers earlier

chore: minor clang-format tweak, add full stdlib to PCH.h

---

CommonLibSF/include/RE/B/BSStringPool.h

- Also replaces `_InterlockedExchangeAdd` with `stl::atomic_ref` to be consistent with other atomic usage

chore: remove redundant `BSStringPool` template specialization

---

CommonLibSF/include/RE/A/AIProcess.h
CommonLibSF/include/RE/A/Actor.h
CommonLibSF/include/RE/A/ActorPackage.h
CommonLibSF/include/RE/Starfield.h
CommonLibSF/src/RE/A/AIProcess.cpp
CommonLibSF/src/RE/A/ActorPackage.cpp

Adds AIProcess struct, the fields line up with CommonLibF4.

feat: `Actor`, `AIProcess`, `ActorPackage` RE

---

CommonLibSF/include/REL/Version.h
CommonLibSF/include/SFSE/Interfaces.h
CommonLibSF/src/REL/ID.cpp

- set default separator to `.`
- simplify `SetOrClearBit`

feat!: make plugin version return Version instead

---

CommonLibSF/src/REL/ID.cpp

So users can check where it's supposed to be located. Very useful for Gamepass users.

feat: Add details to the error "Failed to find address library".

---

CommonLibSF/src/REL/ID.cpp

While testing the Address Lib with `SFSE` I noticed that CommonLibSF wasn't detecting the `kMsStore` platform correctly as `XGameRuntime` does not exist in the game folder. Changing this to `Xcurl` solved the issue. I tweaked the path to remove an extra '/' after the game version.
Hopefully I followed the contrib guidlines correctly, apologies if I didnt.

fix: Updated VendorModule to detect kMsStore platform correctly and fixed the path accordingly.

---

.github/workflows/main_ci.yml
.github/workflows/main_ci_xmake.yml
CommonLibSF/include/SFSE/Impl/PCH.h

I had to comment out two includes (`stdfloat` and `print`) due to CI not using a newer version of the toolset (14.37) which includes these features.
https://en.cppreference.com/w/cpp/compiler_support/23

chore: add xmake ci

---

CommonLibSF/include/RE/B/BGSAttachParentArray.h
CommonLibSF/include/RE/B/BGSAttackDataForm.h
CommonLibSF/include/RE/B/BGSDestructibleObjectForm.h
CommonLibSF/include/RE/B/BGSForcedLocRefType.h
CommonLibSF/include/RE/B/BGSKeywordForm.h
CommonLibSF/include/RE/B/BGSMod.h
CommonLibSF/include/RE/B/BGSNativeTerminalForm.h
CommonLibSF/include/RE/B/BGSObjectPlacementDefaults.h
CommonLibSF/include/RE/B/BGSOverridePackCollection.h
CommonLibSF/include/RE/B/BGSPerkRankArray.h
CommonLibSF/include/RE/B/BGSPropertySheet.h
CommonLibSF/include/RE/B/BGSSkinForm.h
CommonLibSF/include/RE/B/BGSTypedKeywordValueArray.h
CommonLibSF/include/RE/C/Color.h
CommonLibSF/include/RE/T/TESAIForm.h
CommonLibSF/include/RE/T/TESActorBase.h
CommonLibSF/include/RE/T/TESActorBaseData.h
CommonLibSF/include/RE/T/TESBoundAnimObject.h
CommonLibSF/include/RE/T/TESBoundObject.h
CommonLibSF/include/RE/T/TESContainer.h
CommonLibSF/include/RE/T/TESNPC.h
CommonLibSF/include/RE/T/TESObject.h
CommonLibSF/include/RE/T/TESRaceForm.h
CommonLibSF/include/RE/T/TESSpellList.h
CommonLibSF/src/RE/C/Color.cpp

- **breaking** - moved pronoun enum from `TESActorBase` to `TESNPC` class (where it should have been) and renamed it to match other enum usage  (#131 )
- added missing static asserts and virtual destructor overrides

feat!: `TESNPC` and related classes RE

---

CommonLibSF/xmake-extra.lua
CommonLibSF/xmake.lua

- this simplifies the experience of having `commonlibsf` as a submodule when using xmake for the purposes of local modifications
- does not expose any additional options at the moment, like changing `UsesAdressLibrary` or `IsLayoutDependent`, because I'm tired. They can be added later if necessary.

feat: add xmake plugin rule for submodule use

---

CommonLibSF/include/RE/B/BGSForcedLocRefType.h
CommonLibSF/include/RE/B/BGSMod.h
CommonLibSF/include/RE/B/BGSPerkRankArray.h
CommonLibSF/include/RE/P/PerkRankData.h
CommonLibSF/include/RE/T/TESContainer.h
CommonLibSF/include/RE/T/TESSpellList.h

- `PerkRankData` has been split into its own header since it's also used in `Actor` class

feat: formcomponent definitions

---

CommonLibSF/include/RE/P/PlayerCharacter.h

I'm not entirely sure about TESObjectREFR* crosshairRef(should it be NiPointer<TESObjectREFR> crosshairRef?) but it works nonetheless.

feat: RE PlayerCharacter further

---

CommonLibSF/include/REL/ID.h
CommonLibSF/include/REL/Version.h
CommonLibSF/include/SFSE/IAT.h
CommonLibSF/include/SFSE/Impl/PCH.h
CommonLibSF/include/SFSE/InputMap.h
CommonLibSF/include/SFSE/Trampoline.h
CommonLibSF/include/SFSE/Utilities.h
CommonLibSF/src/REL/ID.cpp
CommonLibSF/src/REL/Module.cpp
CommonLibSF/src/REL/Version.cpp
CommonLibSF/src/SFSE/API.cpp
CommonLibSF/src/SFSE/IAT.cpp
CommonLibSF/src/SFSE/InputMap.cpp
CommonLibSF/src/SFSE/Interfaces.cpp
CommonLibSF/src/SFSE/Logger.cpp

Should be the last of these stupid refactors for a while
- Remove unnecessary `std::move` calls from IAT.h/cpp
- Make a few functions `static`
- Collapse namespaces in PCH.h, InputMap.h, Utilities.h, and Logger.cpp to reduce nesting
- Add `noexcept` to `Trampoline` move ctor and assignment operator
- Fix a variable name hiding previous definition in Module.cpp
- Switch to range-based for loops in Version.cpp
- Fix `a_paramName` convention in InputMap.cpp

refactor: stuff

---

CommonLibSF/include/RE/I/INISettingCollection.h
CommonLibSF/include/RE/R/RegSettingCollection.h
CommonLibSF/include/RE/S/Setting.h

- added helper functions to quickly `Get`/`Set` a setting's value in a collection (if it exists). If `Get` fails, it returns the user provided fallback value. If `Set` fails, it returns false.
- fixed the direct `Setting::GetX` functions returning the wrong value when default is enabled

feat: improve `Settings` & related

---

CommonLibSF/include/RE/B/BSLock.h
CommonLibSF/src/RE/B/BSLock.cpp

- also moved `BSLock` functions to its own source file for better readability

feat: add `BSNonReentrantSpinLock`

---

CommonLibSF/include/RE/B/BSExtraData.h
CommonLibSF/include/RE/E/ExtraDataList.h
CommonLibSF/include/RE/E/ExtraDataTypes.h
CommonLibSF/include/RE/T/TESObjectCELL.h
CommonLibSF/include/RE/T/TESObjectREFR.h

- `EXTRA_DATA_TYPE` was renamed to `ExtraDataType` for consistency (ie. match `FormType` enum)

feat!: add `ExtraDataList`, `BSExtraData`

---

CMakeLists.txt
CommonLibSF/CMakeLists.txt
CommonLibSF/CMakePresets.json

- Remove `VERSION` field from `project()` call in CMakeLists.txt
- Enable `CMAKE_OPTIMIZE_DEPENDENCIES`
- Remove unused `CMAKE_SHARED_LINKER_FLAGS_<CONFIG>` cache variables from CMakePresets.json
- Formatting

chore: CMakeLists and CMakePresets cleanup

---

.github/workflows/main_ci.yml
.github/workflows/update_pdb.yml
CommonLibSF/CMakeLists.txt
CommonLibSF/CMakePresets.json
CommonLibSF/cmake/CPM.cmake
README.md
build-clang-cl.bat
build-msvc.bat
make-sln-clang-cl.bat
make-sln-msvc.bat

Non-breaking, adds CPM as an alternative to vcpkg via additional build presets.
Closes #189

feat: add CPM.cmake

---

CommonLibSF/include/RE/IDs.h
CommonLibSF/include/RE/M/msvc.h
CommonLibSF/include/RE/RTTI.h
CommonLibSF/include/SFSE/Impl/PCH.h

Ported from CommonLibF4. The only new thing is a new deleter, `AlignedDelete`, for `msvc::unique_ptr`. 
Not sure how this should be organized; if this should be left in one file, divided into multiple files, or moved to SFSE::impl

feat: add msvc::unique_ptr, function, fill out type_info

---

.github/workflows/main_ci.yml
CommonLibSF/CMakeLists.txt
CommonLibSF/cmake/make-sourcelist.ps1
CommonLibSF/test/test.cpp

Just builds a cpp file that includes RE/Starfield.h so that we compile all the header files to check for errors, not just the ones that have modules

feat: add SFSE_BUILD_TESTS option

---

CommonLibSF/CMakePresets.json
CommonLibSF/include/RE/D/DebuggerMessages.h
CommonLibSF/include/RE/Starfield.h

Note: I had to set _ITERATOR_DEBUG_LEVEL=0 for both release and debug builds to ensure that both std::vector and std::string did not have their size increased by 8. (std::string is 32 bytes when _ITERATOR_DEBUG_LEVEL=0, 40 bytes otherwise)

feat: Add DebuggerMessages

---

CommonLibSF/CMakePresets.json

chore: add `CMAKE_CONFIGURATION_TYPES` to CMakePresets

---

CommonLibSF/include/RE/D/DebuggerMessages.h

Value Response had incorrect members and size

fix: fix ValueResponse

---

CommonLibSF/include/RE/I/idLogging.h
CommonLibSF/include/RE/I/idTCP.h
CommonLibSF/include/RE/IDs.h
CommonLibSF/include/RE/Starfield.h
CommonLibSF/include/SFSE/Impl/WinAPI.h
CommonLibSF/src/RE/I/idLogging.cpp
CommonLibSF/src/RE/I/idTCP.cpp
CommonLibSF/src/SFSE/Impl/WinAPI.cpp

idTCP uses WinAPI types in its declarations; what is the policy on RE'd files using WinAPI types in their declarations?

feat: add idTCP, idLogging

---

CommonLibSF/include/SFSE/Interfaces.h

This updates the SFSE version data to work with https://github.com/ianpatt/sfse/commit/59a5bba27701982e3522c88488ff3dd9fc61798b. Please do not merge until PR #229 is in.
Plugins releasing between taking this change and the next SFSE update (will either release something with busted class definitions just so plugins are OK, or fix that up and release depending on how long that takes) can call `CompatibleVersions({RUNTIME_SF_1_8_86})` on their version struct to explicitly specify compatibility with the current version of the game.

feat: SFSE plugin version data update for 1.8.86 struct compat break

---

CommonLibSF/include/RE/S/Script.h

There are 16 console commands with command.functionName is nullptr (Steam 1.9.51). I don't know about script commands but I place the same check for consistency.

fix: Small check for command.functionName is not nullptr

---

CommonLibSF/include/SFSE/Version.h

also add missing game versions
0.2.5 is estimated version number

chore: bump latest SFSE version to 0.2.5

---

CMakeLists.txt

The existing 'add-file.ps1' script still works for adding classes into their correctly-lettered folders etc, as the globbing from this change will pick those new files up anyway.

fix: changed build to glob files without powershell

---

scripts/IDAPDB.py

This is something I've been using for reverse engineering; basically, the script takes in a PDB file (preferrably the test PDB) and removes the `RE` and `SFSE` namespace from everything, then outputs a new PDB. This makes it a lot easier to sync types with IDA (especially since if you've been using the mangled names from the Fallout 4 DB for everything)

feat: Add IDA pdb generator script

---

include/RE/A/Actor.h

TESObjectREFR was changed by -20 bytes, but also one Actor member had a repeated offset (unk368 vs race).

fix: actor offsets

---

CMakeLists.txt
CMakePresets.json

Moving the compiler flags to cmakelists gives oportunity to use cmake ports. To build using cmake ports "/D_ITERATOR_DEBUG_LEVEL=0" is needed. If the other flags aren't being used I can remove them.

build: Move compile flags to CMakeLists

---

include/RE/C/ConsoleLog.h
include/RE/IDs.h
include/REL/Relocation.h
include/REX/W32.h
include/REX/W32/BASE.h
include/REX/W32/NT.h
src/REX/W32.cpp

- the fast and furious series has a lot of sequels

feat!: miscX

---

include/RE/T/TESActorBase.h
include/RE/T/TESActorBaseData.h
include/RE/T/TESNPC.h

- the inheritance offset markers are probably wrong, but that doesn't really matter right now.

fix: `TESNPC`

---

include/RE/B/BGSMod.h
include/RE/T/TESObjectWEAP.h

TESObjectWEAP
- New Classes Added: Introduced several classes related to weapon data handling, including:
- WeaponAmmoData, WeaponDamageData, WeaponFiringData, WeaponDataFlags, WeaponDataGeneral, WeapDataMelee, WeaponDataPower, WeapDataReload, WeapDataTurret, WeapDataVariableRange, WeapDataVisuals, WeapDataShipWeapon, WeaponDataAudio, WeaponDataCharge, and WeaponDataAim.
- Class TESObjectWEAPInstanceData Updated: Modified to include pointers to these new weapon data classes.
- Static Assertions Added: Included multiple static_assert statements to validate offsets within the new classes, ensuring proper memory alignment for each member variable.
BGSMod
- New Class (`BGSAddonNode`): Added to the `RE` namespace.
- Property Structure: Introduced a new `Property` structure inside `Data`, …

feat: Updated BGSMod and TESObjectWEAP headers

---

include/REL/Relocation.h
include/SFSE/Utilities.h

changes:
* add second template arg to applicable `Relocation::write_` funcs for address offset
* remove `AllocTrampoline` from `stl::write_*` funcs, this is bad practice
* normalize `stl::write_*` support for structs with `std::uintptr_t`, `REL::ID`, `REL::Offset`, `REL::Relocation<std::uintptr_t>` static `address` members

feat: improve `Relocation` & `Utilities`
